# 
# Do not Edit! Generated by:
# spectacle version 0.15
# 
# >> macros
# << macros

Name:       swig
Summary:    Connects C/C++/Objective C to some high-level programming languages
Version:    1.3.40
Release:    1
Group:      Development/Tools
License:    BSD
URL:        http://swig.sourceforge.net
Source0:    http://download.sourceforge.net/swig/swig-%{version}.tar.gz
Source1:    swig-rpmlintrc
Source100:  swig.yaml
Patch0:     swig-1.3.23-pylib.patch
BuildRequires:  perl
BuildRequires:  python-devel

%description
SWIG is a software development tool that connects programs written in C
and C++ with a variety of high-level programming languages. SWIG is 
primarily used with common scripting languages such as Perl, PHP, Python,
Tcl/Tk, and Ruby, however the list of supported languages also includes
non-scripting languages such as C#, Common Lisp (CLISP, Allegro CL, UFFI),
Java, Modula-3, OCAML, Octave, and R. Also several interpreted and compiled
Scheme implementations (Guile, MzScheme, Chicken) are supported. SWIG is 
most commonly used to create high-level interpreted or compiled programming 
environments, user interfaces, and as a tool for testing and prototyping C/C++
software. SWIG can also export its parse tree in the form of XML and Lisp
s-expressions.



%package doc
Summary:    Documentation files for %{name}
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
Description: %{summary}


%prep
%setup -q -n %{name}-%{version}

# swig-1.3.23-pylib.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post









%files
%defattr(-,root,root,-)
# >> files
%doc LICENSE
%{_bindir}/*
%{_datadir}/swig
/usr/share/man/man1/ccache-swig.1.gz
# << files


%files doc
%defattr(-,root,root,-)
# >> files doc
%doc ANNOUNCE CHANGES FUTURE INSTALL NEW README TODO
%doc Doc/*
# << files doc

